export const VIDEO_OPERATION = 'VIDEO_OPERATION';
export const VIDEO_SRC_CHANGE = "VIDEO_SRC_CHANGE";
export const VIDEO_CURRENTTIME_CHANGE = "VIDEO_CURRENTTIME_CHANGE";
export const RESULT_TIMETABLE_ADD = "RESULT_TIMETABLE_ADD";
export const RESULT_TIMETABLE_UPDATE = "RESULT_TIMETABLE_UPDATE";
export const RESULT_TIMETABLE_DELETE = "RESULT_TIMETABLE_DELETE";
export const RESULT_TIMETABLE_SELECT = "RESULT_TIMETABLE_SELECT";
export const SCORE_INNING_CHANGE = "SCORE_INNING_CHANGE";
